### ISSUE TITLE
Support for master-detail?

### ISSUE THREAD

**Issue by plotters** [Skycoder42/QtDataSync#1]
Is it possible to use QtDataSync with master-detail? In that case dataType 1 (master) has a relationship with dataType 2 (detail). When selecting a row in the view, only items which belong dataType 1 will be shown in the detail view.

**Comment by Skycoder42** [comment]
It is of course possible, but not integrated into the library itself, as it was designed as a document store, not a relational data model.

You can however easily replicate that behavior manually. The fastest way would be to use a id property for the detail data that contains the masters id, e.g.
```
Master: someId
Detail: someId/detail1
```

This way you can use `DataStore::search` to only get relevant details objects.

But it is also possible to archive this on application level by using filter models that do basically the same thing before displaying data. However, this might become problematic when working with huge datasets.

**Comment by plotters** [comment]
Thanks for the advice. In the end using `QSortFilterProxyModel` works indeed great to filter the data based on `someId`. Like this (`_sortModel2` = detail, `_sortModel` = master, `someId` is column 2

`_sortModel2->setFilterKeyColumn(2);`
`_sortModel2->setFilterFixedString(QString::number(someId));`
