### ISSUE TITLE
Cannot upgrade QtDataSync to 4.2.3 using AUR

### ISSUE THREAD

**Issue by plotters** [Skycoder42/QtDataSync#3]
Error I get is:

```
error: failed to commit transaction (conflicting files)
qt5-datasync-doc: /usr/share/man/man3/typedef.3.gz exists in filesystem (owned by qt5-service-doc)
Errors occurred, no packages were upgraded.

```
First upgrading qt5-service-doc does not help. Had to upgrade from 4.2.2. due to new crypto++ version which was installed system wide. 

OS: Linux 4.19.42-1-MANJARO

**Comment by Skycoder42** [comment]
Oh okay. Apparently, manfiles generated by doxygen can conflict with each other. Thats bad news, but man pages where only added as a bonus - the ones generated by doxygen aren't that great anyways.

As a workaround, simply uncomment the line that installs them, see [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qt5-datasync#n94). In future versions, I will remove that line permanently.

**Comment by plotters** [comment]
Thanks, that works, cloned https://aur.archlinux.org/qt5-datasync.git locally and edited the PKGBUILD file. Then `makepkg -si` and I could install version 4.2.3
